artipie/helm-adapter

src/test/java/com/artipie/helm/TarArchiveTest.java

This Pull Request adds a test which ensures that `TgzArchive#save` works perfectly fine.
Related to #19

Ensure tgz#save works correctly

---

pom.xml
src/main/java/com/artipie/helm/HelmSlice.java

`Multiple` has been replaced with `Any`. The push slice is triggered on POST or PUT request. Before it was not triggered at all
Related to #1

Update slice to work properly

---

src/main/java/com/artipie/helm/PushChartSlice.java
src/main/java/com/artipie/helm/TgzArchive.java
src/main/java/com/artipie/helm/metadata/IndexYaml.java
src/main/java/com/artipie/helm/metadata/IndexYamlMapping.java
src/main/java/com/artipie/helm/metadata/package-info.java
src/test/java/com/artipie/helm/IndexYamlTest.java
src/test/resources/index.yaml

Part of #84  
Deleting by chart name was implemented. 
`IndexYamlMapping` was created to simplify working with `index.yaml` file. 
Added `@todo` to remove code duplication.
I am not sure about throwing exception for `Completable` with `doOnError`.

#84 - Implement deleting by chart name

---

src/main/java/com/artipie/helm/metadata/IndexYaml.java
src/main/java/com/artipie/helm/metadata/IndexYamlMapping.java

Closes #86 
Removed code duplication in `IndexYaml`.
Added `IndexYamlMapping#addChart` to extract logic from `IndexYaml#update`

#86 - Remove code duplication in IndexYaml

---

src/main/java/com/artipie/helm/metadata/IndexByDirectory.java
src/main/java/com/artipie/helm/metadata/IndexYaml.java
src/main/java/com/artipie/helm/metadata/IndexYamlMapping.java
src/test/java/com/artipie/helm/metadata/IndexByDirectoryTest.java

Part of #90 
Added negative test cases for `IndexByDirectory`. Used `toString()` in `IndexYaml`

#90 - Add negative tests for IndexByDirectory

---

src/main/java/com/artipie/helm/metadata/IndexByDirectory.java
src/main/java/com/artipie/helm/metadata/IndexYaml.java
src/main/java/com/artipie/helm/metadata/IndexYamlMapping.java
src/test/java/com/artipie/helm/HelmSliceIT.java
src/test/java/com/artipie/helm/metadata/IndexByDirectoryTest.java

Closes #90 
Implemented generating index by directory not using existing `index.yaml` file with info about charts.

#90 - Generate index by directory not using existing

---

src/main/java/com/artipie/helm/metadata/IndexByDirectory.java
src/main/java/com/artipie/helm/metadata/IndexMerging.java
src/main/java/com/artipie/helm/metadata/IndexYaml.java
src/main/java/com/artipie/helm/metadata/IndexYamlMapping.java
src/test/java/com/artipie/helm/HelmSliceIT.java
src/test/java/com/artipie/helm/IndexYamlTest.java
src/test/java/com/artipie/helm/metadata/IndexByDirectoryTest.java
src/test/java/com/artipie/helm/metadata/IndexMergingTest.java
src/test/resources/merge/output/index.yaml
src/test/resources/merge/remote/index.yaml
src/test/resources/merge/source/index.yaml

Closes #89 
Implemented merging `index.yaml` files. For testing, I used file that was obtained after merge two indexes with command
`helm repo index --merge index.yaml --url http://charts.helm.sh/charts/ ./`

#89 - Merge `index.yaml` files

---

pom.xml
src/main/java/com/artipie/helm/http/DownloadIndexSlice.java
src/main/java/com/artipie/helm/http/HelmSlice.java
src/main/java/com/artipie/helm/http/PushChartSlice.java
src/main/java/com/artipie/helm/http/package-info.java
src/main/java/com/artipie/helm/metadata/IndexMerging.java
src/main/java/com/artipie/helm/metadata/IndexYaml.java
src/test/java/com/artipie/helm/HelmCompatibilityITCase.java
src/test/java/com/artipie/helm/HelmSliceIT.java
src/test/java/com/artipie/helm/IndexYamlTest.java
src/test/java/com/artipie/helm/http/BufsToByteArrTest.java
src/test/java/com/artipie/helm/http/package-info.java
src/test/java/com/artipie/helm/metadata/IndexMergingTest.java
src/test/resources/index.yaml

Part of #96 
Stopped using prefix in `PushChartSlice` because now urls are got by dynamically combining. For this purpose, `DownloadIndexSlice` was introduced. 
Bumped dependency of testcontainers from 1.14.3 to 1.15.1 to fix ITs failings.

#96 - Add prefix during download, not use prefix when pushing

---

src/main/java/com/artipie/helm/Helm.java
src/main/java/com/artipie/helm/metadata/Index.java
src/test/java/com/artipie/helm/HelmAstoAddTest.java
src/test/resources/index/index-one-ark.yaml

Part of #109 
Added implementation of add operation for several packages. Info about packages with specified version should be absent in existed `index.yaml`. Basically it reads existed index line by line and adds information for specified packages. This information is git from tgz archive with charts.
Some crucial test cases were added but now they are diasbled.

Add implementation of add for several packages

---

src/main/java/com/artipie/helm/Helm.java
src/main/java/com/artipie/helm/metadata/Index.java
src/main/java/com/artipie/helm/metadata/ParsedChartName.java
src/main/java/com/artipie/helm/metadata/YamlWriter.java
src/test/java/com/artipie/helm/HelmAstoAddTest.java
src/test/java/com/artipie/helm/metadata/ParsedChartNameTest.java
src/test/resources/index/index-one-ark-four-spaces.yaml

Part of #117
Extracted yaml writer for index file, this file encapsulates required indents and instance of buffered writer. 
Also, extracted class for validation of parsed name.
Added test for case when there are four spaces in source index file.

Extract writer for index and class for parsed name validation

---

src/main/java/com/artipie/helm/Helm.java
src/test/java/com/artipie/helm/HelmAstoDeleteTest.java

Part of #109 
Add skeleton for deletion charts by keys. Some negative tests cases were also added

Add skeleton for deletion charts

---

src/main/java/com/artipie/helm/Charts.java
src/main/java/com/artipie/helm/ChartsWriter.java
src/main/java/com/artipie/helm/Helm.java
src/test/java/com/artipie/helm/ChartsAstoVersionsForTest.java

Part of #117 
Extracted `Charts` interface for obtaining info about passed charts as keys from storage.
Extracted `ChartsWriter` for combining info from chart yaml files from storage by passed keys and content of existed index file.
Next I'll add test for `Charts.Asto#versionsAndYamlFor` and for `ChartsWriter`

Extract `Charts` interface and `ChartsWriter`

---

src/test/java/com/artipie/helm/ChartsAstoTest.java
src/test/java/com/artipie/helm/ChartsWriterTest.java

Part of #117 
Added tests for `ChartsWriter` and for obtaining versions for charts from storage by passed keys.

Add tests for `ChartsWriter` and for obtaining versions for charts

---

src/main/java/com/artipie/helm/ChartsWriter.java
src/main/java/com/artipie/helm/Helm.java
src/test/java/com/artipie/helm/ChartsWriterTest.java
src/test/java/com/artipie/helm/HelmAstoDeleteTest.java

Part of #109 
Finished implementation of `remove(Collection)`. 
Added more tests for different cases.
Fixed problem that related tgz archive of charts were not removed.
Added todo for refactoring `ChartsWriter`.

Finish implementation of `remove`, add tests

---

src/main/java/com/artipie/helm/AddWriter.java
src/main/java/com/artipie/helm/Helm.java
src/main/java/com/artipie/helm/RemoveWriter.java
src/main/java/com/artipie/helm/metadata/Index.java
src/test/java/com/artipie/helm/HelmAstoDeleteTest.java
src/test/java/com/artipie/helm/RemoveWriterAstoTest.java
src/test/java/com/artipie/helm/metadata/IndexWithBreaksTest.java

Part of #139 
Added prefix for `remove` operation. Added tests for verifying deletion for nested archives.
Removed `failsToDeleteAbsentChartIfTgzIsAbsent()` tests from `RemoveWriterAstoTest` as `RemoveWriterAsto` doesn't work now with archives from storage and accepts now `Map<String, Set<String>>`. This negative scenario is covered in `HelmAstoDeleteTest`

Add prefix for `remove` operation

---

src/main/java/com/artipie/helm/AddWriter.java
src/main/java/com/artipie/helm/ChartYaml.java
src/test/java/com/artipie/helm/AddWriterAstoTest.java

Part of #105 
Added method in `AddWriter` for adding info about charts to index trustfully. It means that existed index does not check somehow and info about all passed charts is added to a new index. Info doesn't check somehow in existed index file because anyway it is necessary to extract chart info from archive

Add method in `AddWriter` for adding charts trustfully

---

src/main/java/com/artipie/helm/http/DeleteChartSlice.java
src/test/java/com/artipie/helm/HelmSliceIT.java
src/test/java/com/artipie/helm/http/DeleteChartSliceTest.java
src/test/java/com/artipie/helm/http/HelmDeleteIT.java

Closes #106 
Added IT for `DeleteChartSlice`. Changed route path according to [this](https://github.com/helm/chartmuseum#chart-manipulation)

Add IT for delete chart operation, fix path

---

pom.xml
src/main/java/com/artipie/helm/Charts.java
src/test/java/com/artipie/helm/TgzArchiveTest.java
src/test/java/com/artipie/helm/http/HelmDeleteIT.java

Closes #29 
Part of #180 
Eliminated using of  classes from `io.vertx.core.impl` by refactoring test and excluded `com.fasterxml.jackson.core`

Enhance `TgzArchive` test, exclude `com.fasterxml.jackson.core`

---

pom.xml
src/main/java/com/artipie/helm/metadata/Index.java
src/test/java/com/artipie/helm/metadata/IndexWithBreaksTest.java

Part of #113 
Use reactive tokenizer instead of copying index file in temporary file. Changed a bit test because now it is not necessary to check existence of temporary directories.

Use tokenizer instead of copying index in `Index.WithBreaks`

---

src/main/java/com/artipie/helm/AddWriter.java
src/main/java/com/artipie/helm/Helm.java
src/main/java/com/artipie/helm/RemoveWriter.java
src/main/java/com/artipie/helm/metadata/Index.java
src/test/java/com/artipie/helm/RemoveWriterAstoTest.java
src/test/resources/index/index-four-spaces.yaml

Closes #113 
Use reactive tokenizer for `remove` instead of copying index file in temporary file. Now it reads line by line from source file and write a new index to a temporary file which at the end replaces source index file.
Also fix test file which should contain four spaces instead of two

Use tokenizer instead of copying index for `delete`
