artipie/helm-adapter

- .gitattributes
- LICENSE
- README.md
- pom.xml
- src/main/java/com/artipie/helm/package-info.java
- src/test/java/com/artipie/helm/package-info.java
> setup + link in readme with docs

- pom.xml
- src/main/java/com/artipie/helm/IndexYaml.java
- src/main/java/com/artipie/helm/PushChartSlice.java
- src/main/java/com/artipie/helm/TgzArchive.java
This pull request creates a structure for #12 implementation with 4 different puzzles
> Add structure

- src/main/java/com/artipie/helm/PushChartSlice.java
- src/test/java/com/artipie/helm/BufsToByteArrTest.java
> Implement memory

- src/main/java/com/artipie/helm/TgzArchive.java
> Reimplement with slices

- src/main/java/com/artipie/helm/TgzArchive.java
- src/test/java/com/artipie/helm/TgzArchiveTest.java
This is for #19.
Apparently the test was already there, so I added another one and corrected the test file name as well as made a method private since it wasn't meant to be exposed.
> (#19) - Improve tests for TgzArchive

- .github/workflows/maven.yml
- src/main/java/com/artipie/helm/ChartYaml.java
- src/main/java/com/artipie/helm/IndexYaml.java
Implements IndexYaml#update
_Closes #32
> Implement update

- src/main/java/com/artipie/helm/IndexYaml.java
> Implement Index#empty

- pom.xml
- src/main/java/com/artipie/helm/IndexYaml.java
- src/main/java/com/artipie/helm/TgzArchive.java
Completes the digest puzzle #40
> Implement digest

- src/main/java/com/artipie/helm/HelmSlice.java
- src/main/java/com/artipie/helm/IndexYaml.java
- src/main/java/com/artipie/helm/PushChartSlice.java
Implement urls field in Index.yaml #38
> Implement urls

- src/main/java/com/artipie/helm/IndexYaml.java
Formatting and generation have been improved to look more like a file generated by `helm` utility:
1. Formatted in block style
2. Set for `urls` field has been replaced with list
3. An entry is generated if it did not exist before
Related to #8
> Improved formatting for index.yaml file

- README.md
> Add a section on how to upload a chart

- src/main/java/com/artipie/helm/HelmSlice.java
> Auth support

- pom.xml
- src/main/java/com/artipie/helm/HelmSlice.java
- src/test/java/com/artipie/helm/HelmSliceIT.java
- src/test/java/com/artipie/helm/TgzArchiveTest.java
Updated dependencies and fixed compilation issues
> Bumped ppom, http and asto

- pom.xml
- src/main/java/com/artipie/helm/HelmSlice.java
Closes #72 
HTTP upgraded to 0.16.7, migrated to `BasicAuthSlice`
> #72 - HTTP upgraded to 0.16.7, migrated to BasicAuthSlice

- src/main/java/com/artipie/helm/IndexYaml.java
- src/test/java/com/artipie/helm/IndexYamlTest.java
Closes #41 
Add test to verify digest from `index.yaml`
> #41 - Verify digest from index.yaml

- src/test/java/com/artipie/helm/HelmCompatibilityITCase.java
> #81 - Fix ITCase

- src/main/java/com/artipie/helm/ChartYaml.java
- src/main/java/com/artipie/helm/http/DownloadIndexSlice.java
- src/main/java/com/artipie/helm/http/HelmSlice.java
- src/test/java/com/artipie/helm/HelmSliceIT.java
- src/test/java/com/artipie/helm/http/DownloadIndexSliceTest.java
- src/test/resources/index/invalid_uri.yaml
Closes #96 
Added unit tests for `DownloadInexSlice`
> #96 - Add unit tests for DownloadInexSlice

- pom.xml
- src/main/java/com/artipie/helm/Helm.java
- src/main/java/com/artipie/helm/http/PushChartSlice.java
- src/test/java/com/artipie/helm/http/PushChartSliceTest.java
Part of #109 
Added skeleton for batch update. 
Added parameter to disable index update for single upload in `PushChartSlice and tested it`
> Add skeleton for batch update, add parameter to disable index update

- src/main/java/com/artipie/helm/Helm.java
- src/main/java/com/artipie/helm/metadata/EmptyIndex.java
- src/main/java/com/artipie/helm/metadata/IndexYaml.java
- src/main/java/com/artipie/helm/metadata/IndexYamlMapping.java
- src/main/java/com/artipie/helm/misc/DateTimeNow.java
- src/main/java/com/artipie/helm/misc/EmptyIndex.java
- src/main/java/com/artipie/helm/misc/package-info.java
Closes #115 
Refactored a bit by extracting class for obtaining date and empty index file
> Extract classes for obtaining date and empty index file

- pom.xml
- src/main/java/com/artipie/helm/Helm.java
- src/test/java/com/artipie/helm/HelmAstoAddTest.java
Part of #109 
Added tests for `add` operation, fix some bugs in implementation
> Add tests and fix bugs for `add`

- src/main/java/com/artipie/helm/ChartsWriter.java
- src/main/java/com/artipie/helm/Helm.java
- src/test/java/com/artipie/helm/HelmAstoDeleteTest.java
Closes #117 
Part of #109 
Refactored `Helm`, added partially writer for deletion operation (e. g. removing some charts from existed index file)
> Refactor `Helm`, add partially writer for deletion

- src/main/java/com/artipie/helm/AddWriter.java
- src/main/java/com/artipie/helm/ChartsWriter.java
- src/main/java/com/artipie/helm/Helm.java
- src/main/java/com/artipie/helm/RemoveWriter.java
- src/test/java/com/artipie/helm/AddWriterAstoTest.java
- src/test/java/com/artipie/helm/ChartsWriterTest.java
Part of #134 
Extracted `AddWriter` for dividing of charts writer in two different parts for `add` and `remove` operations
> Extract `AddWriter`, added implementation for `Asto`

- src/main/java/com/artipie/helm/AddWriter.java
- src/main/java/com/artipie/helm/ChartsWriter.java
- src/main/java/com/artipie/helm/metadata/Index.java
- src/main/java/com/artipie/helm/misc/LineWriter.java
Part of #134 
Modified obtaining versions by packages from index file to avoid using method for checking existence of index. 
Also, extracted class for writer which replaces tag `generated`.
> Extract common part for add and remove operations

- pom.xml
- src/main/java/com/artipie/helm/AddWriter.java
- src/main/java/com/artipie/helm/Helm.java
- src/main/java/com/artipie/helm/RemoveWriter.java
- src/main/java/com/artipie/helm/TgzArchive.java
- src/main/java/com/artipie/helm/http/DownloadIndexSlice.java
- src/main/java/com/artipie/helm/metadata/Index.java
- src/test/java/com/artipie/helm/HelmAstoDeleteTest.java
- src/test/java/com/artipie/helm/RemoveWriterAstoTest.java
- src/test/java/com/artipie/helm/http/DownloadIndexSliceTest.java
- src/test/java/com/artipie/helm/http/IndexMergingSliceTest.java
> Bump `asto` to 1.1.0

- benchmarks/src/main/java/com/artipie/helm/HelmAstoAddBench.java
Part of #121 
Added benchmark for `add` operation
> Add benchmark for `add` operation

- README.md
Closes #121 
Added info about benchmarking to readme
> Add benchmarking to readme

- benchmarks/pom.xml
- benchmarks/src/main/java/com/artipie/helm/HelmAstoAddBench.java
Closes #160 
Fixed pom for benchmarks by adding dependency. Remove `bench` profile
> Fix pom of benchmarks

- CHANGELOG
- src/main/java/com/artipie/helm/http/DeleteChartSlice.java
- src/main/java/com/artipie/helm/http/HelmSlice.java
- src/test/java/com/artipie/helm/http/DeleteChartSliceTest.java
Part of #106 
Added slice for deleting chart by name or by name and version.
Also added tests for this slice
> Added `DeleteChartSlice`

- benchmarks/src/main/java/com/artipie/helm/HelmAstoReindexBench.java
Part of #169 
Added benchmark for `reindex` operation of SDK API
> Added benchmark for `reindex`

- benchmarks/run-bench.sh
Part of #169 
Fix condition in script for benchmarks as now it return `true`  in any case
> Fix condition in script for running benchmarks

- src/main/java/com/artipie/helm/ChartYaml.java
> Use `SafeConstuctor` for yaml parser
